apiVersion: 1
datasources:
  - name: Agent Prometheus
    uid: agent-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s
  - name: Agent Tempo
    uid: agent-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
